apiVersion: v2
name: affine
description: AFFiNE cloud chart
type: application
version: 0.1.0
appVersion: "0.25.2"
dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "23.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
