replicaCount: 1

image:
  repository: ghcr.io/toeverything/affine
  tag: ""
  pullPolicy: IfNotPresent

postgresql:
  enabled: false
  auth:
    username: postgres
    password: password
    database: affine
  primary:
    persistence:
      size: 10Gi

redis:
  enabled: false
  auth:
    enabled: false
  master:
    persistence:
      size: 8Gi

smtp:
  host:
    value: ""
    secret:
      name: ""
      key: "smtp-host"
  port:
    value: "465"
    secret:
      name: ""
      key: "smtp-port"
  username:
    value: ""
    secret:
      name: ""
      key: "smtp-user"
  password:
    value: ""
    secret:
      name: ""
      key: "smtp-password"
  sender:
    value: ""
    secret:
      name: ""
      key: "smtp-sender"
  secure: true

deploymentAnnotations: {}

resources:
  requests:
    cpu: "2"
    memory: 2Gi

baseFqdn: ""

persistence:
  enabled: false
  storageClass: ""
  size: 10Gi
  accessMode: ReadWriteOnce

externalDatabase:
  host: ""
  port: "5432"
  username:
    value: ""
    secret:
      name: ""
      key: "db-username"
  password:
    value: ""
    secret:
      name: ""
      key: "db-password"
  database: ""

externalRedis:
  host: ""
  port: "6379"
  username: ""
  password:
    value: ""
    secret:
      name: ""
      key: "redis-password"
  database: 0

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: affine.local
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
