apiVersion: v2
name: wakapi
description: A minimalist, self-hosted WakaTime-compatible backend for coding statistics
type: application
version: 0.1.0
appVersion: 2.16.1
dependencies:
  - name: common
    version: 28.x.x
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
