apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "affine.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: affine
  template:
    metadata:
      labels:
        app: affine
    spec:
      initContainers:
      - name: migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
        env:
        {{- include "affine.commonEnv" . | nindent 8 }}
      containers:
      - name: affine
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        {{- include "affine.commonEnv" . | nindent 8 }}
        ports:
        - containerPort: 3000
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /root/.affine/storage
          subPath: upload
        - name: data
          mountPath: /root/.affine/config
          subPath: config
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "affine.fullname" . }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "affine.fullname" . }}
spec:
  selector:
    app: affine
  ports:
  - port: 3000
