apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "affine.fullname" . }}-web
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: affine-web
  template:
    metadata:
      labels:
        app: affine-web
    spec:
      containers:
      - name: web
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
        env:
        - name: AFFINE_ENV
          value: {{ .Release.Namespace }}
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "affine.fullname" . }}-web
spec:
  selector:
    app: affine-web
  ports:
  - port: 8080
