{{- if .Values.ai.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy.fullname" . }}-ai
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: appflowy-ai
  template:
    metadata:
      labels:
        app: appflowy-ai
    spec:
      containers:
      - name: ai
        image: {{ .Values.ai.image.repository }}:{{ .Values.ai.image.tag }}
        env:
        - name: OPENAI_API_KEY
          {{- include "appflowy.openaiApiKey" . | nindent 10 }}
        - name: DEFAULT_AI_MODEL
          value: {{ .Values.ai.defaultModel }}
        - name: DEFAULT_AI_COMPLETION_MODEL
          value: {{ .Values.ai.defaultCompletionModel }}
        - name: APPFLOWY_S3_ACCESS_KEY
          value: {{ .Values.appflowy.s3.accessKey | quote }}
        - name: APPFLOWY_S3_ACCESS_KEY
          {{- include "appflowy.s3AccessKey" . | nindent 10 }}
        - name: APPFLOWY_S3_SECRET_KEY
          {{- include "appflowy.s3SecretKey" . | nindent 10 }}
        - name: APPFLOWY_S3_BUCKET
          value: {{ .Values.appflowy.s3.bucket | quote }}
        - name: APPFLOWY_S3_REGION
          value: {{ .Values.appflowy.s3.region | quote }}
        {{- if not .Values.postgresql.enabled }}
        - name: DB_USERNAME
          {{- include "appflowy.dbUsername" . | nindent 10 }}
        - name: DB_PASSWORD
          {{- include "appflowy.dbPassword" . | nindent 10 }}
        {{- end }}
        {{- if and (not .Values.redis.enabled) (or .Values.appflowy.externalRedis.password.value .Values.appflowy.externalRedis.password.secret.name) }}
        - name: REDIS_PASSWORD
          {{- include "appflowy.redisPassword" . | nindent 10 }}
        {{- end }}
        - name: AI_DATABASE_URL
          value: {{ include "appflowy.databaseUrl" . | quote }}
        - name: AI_REDIS_URL
          value: {{ include "appflowy.redisUrl" . | quote }}
        - name: AI_USE_MINIO
          value: {{ .Values.appflowy.s3.useMinio | quote }}
        - name: AI_MINIO_URL
          value: {{ .Values.appflowy.s3.minioUrl | quote }}
        - name: AI_APPFLOWY_HOST
          value: {{ include "appflowy.baseUrl" . | quote }}
        - name: APPFLOWY_GOTRUE_JWT_SECRET
          {{- include "appflowy.jwtSecret" . | nindent 10 }}
        ports:
        - containerPort: 5001
        resources:
          {{- toYaml .Values.ai.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 40
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy.fullname" . }}-ai
spec:
  selector:
    app: appflowy-ai
  ports:
  - port: 5001
{{- end }}
