apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy.fullname" . }}-web
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: appflowy-web
  template:
    metadata:
      labels:
        app: appflowy-web
    spec:
      containers:
      - name: web
        image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
        env:
        - name: APPFLOWY_BASE_URL
          value: {{ include "appflowy.baseUrl" . | quote }}
        - name: APPFLOWY_GOTRUE_BASE_URL
          value: "{{ include "appflowy.baseUrl" . }}/gotrue"
        - name: APPFLOWY_WS_BASE_URL
          value: {{ include "appflowy.baseWsUrl" . | quote }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy.fullname" . }}-web
spec:
  selector:
    app: appflowy-web
  ports:
  - port: 80
